use php-versions.json file to load php version list
Orbitale/Rymfony pull request #51
Opened 2020-12-05 22:09 UTC by macintoshplus

2020-12-06 12:54 UTC, Pierstoval requested changes
Some minor requests, but overall works both on my Windows 10 native setup and WSL too :)

2020-12-06 12:54 UTC, Pierstoval commented on src/commands/php_list.rs
> +            Err(e) => error!("Error on clear cache : {}", e)
```suggestion
            Err(e) => error!("Could not clear binaries cache: {}", e)
```

2020-12-06 12:54 UTC, Pierstoval commented on src/commands/php_list.rs
> +            Ok(_) => info!("Cache cleared"),
```suggestion
            Ok(_) => info!("Binary cache successfully cleared!"),
```

2020-12-06 12:54 UTC, Pierstoval commented on src/config/config.rs
> +        write!(f, "There is an error: {}", self.0)
```suggestion
        write!(f, "An error occured: {}", self.0)
```

2020-12-09 21:26 UTC, Pierstoval requested changes
Small change and we're set 👍

2020-12-09 21:26 UTC, Pierstoval commented on src/commands/php_list.rs
> +            Ok(_) => info!("Binary cache successfully cleared!"),
```suggestion
            Ok(_) => info!("Binaries cache successfully cleared!"),
```

2020-12-10 17:31 UTC, macintoshplus commented
Change applied.

2020-12-10 18:34 UTC, merged

2020-12-10 18:34 UTC, Pierstoval commented
Thanks @macintoshplus